"""add date column

Revision ID: 0b747a2ec2dc
Revises: 4ca0bd23a93b
Create Date: 2020-09-08 23:18:48.383837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b747a2ec2dc'
down_revision = '4ca0bd23a93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'date')
    # ### end Alembic commands ###
